### PR TITLE
Continuation

### PR DESCRIPTION
**Pull request by Serge-NSN**

### CODE REVIEW

**Review by elroykanye — APPROVED** [review]
Exactly. Starting from your import of Random, I just knew everything else was wrong.

**Review by elroykanye — APPROVED** [review]
Valid! First step to thinking like a data scientist. Optimise code.

**Review by elroykanye — CHANGES_REQUESTED** [review]
Exercise 28

Here again, you still use unnecessary long lines of logic.
To check for prime numbers, you are already aware that 0 and 1 are not. The reasonable thing to do is to use a flag variable which is initially false. Then in your loop from 2 to n, if that number , n, is valid then you can change your flag to true. In the end, return flag.

**Review by elroykanye — CHANGES_REQUESTED** [review]
Exercise 29

You keep writing the function over and over when you can just call it from its own module.

If your is_prime function is in sample.py,
"from sample import is_prime" is a reasonable way to extract it from the sample module.

**Comment by Serge-NSN** [comment]
> You keep writing the function over and over when you can just call it from its own module.
> 
> If your is_prime function is in sample.py,
> "from sample import is_prime" is a reasonable way to extract it from the sample module.

okay

**Review by elroykanye — CHANGES_REQUESTED** [review]
Exercise 30 

Avoid using exception handling at all costs. Use your head.
If it's possible that an index error occurs, affix "k" zeros infront of the lesser string where k is their hamming distance.

**Review by elroykanye — APPROVED** [review]
This is the smartest piece of art I have seen today. Good thinking.

**Review by elroykanye — APPROVED** [review]
😂 one line functions are my most admired. Good job!

**Review by elroykanye — CHANGES_REQUESTED** [review]
😂 one line functions are my most admired. Good job! 
However, I want to be sure you can do it yourself.

**Review by elroykanye — APPROVED** [review]

**Review by elroykanye — CHANGES_REQUESTED** [review]
For all exercises necessary


For all functions where you used split or any helper function, rewrite them without using any called functions. Good luck.

**Comment by Serge-NSN** [comment]
>  one line functions are my most admired. Good job!
> However, I want to be sure you can do it yourself.

chai!!

**Comment by Serge-NSN** [comment]
> Avoid using exception handling at all costs. Use your head.
> If it's possible that an index error occurs, affix "k" zeros infront of the lesser string where k is their hamming distance.

hamming distance... saah

**Comment by Serge-NSN** [comment]
> For all functions where you used split or any helper function, rewrite them without using any called functions. Good luck.

I cannot can :(

**Comment by elroykanye** [comment]
> > For all functions where you used split or any helper function, rewrite them without using any called functions. Good luck.
> 
> I cannot can :(

Then drop data science!

**Comment by elroykanye** [comment]
> > Avoid using exception handling at all costs. Use your head.
> > If it's possible that an index error occurs, affix "k" zeros infront of the lesser string where k is their hamming distance.
> 
> hamming distance... saah

Cheap term. Difference in their lengths. Feel free to use len ()

**Comment by Serge-NSN** [comment]
> > > Avoid using exception handling at all costs. Use your head.
> > > If it's possible that an index error occurs, affix "k" zeros infront of the lesser string where k is their hamming distance.
> > 
> > 
> > hamming distance... saah
> 
> Cheap term. Difference in their lengths. Feel free to use len ()

ok

**Comment by elroykanye** [comment]
Share your torture. Tomorrow, consider as a prayer request to God that I should be less cruel. It won't work but just try 😄

**Comment by Serge-NSN** [comment]
> Share your torture. Tomorrow, consider as a prayer request to God that I should be less cruel. It won't work but just try

i thought I've done something.. life is strong.. chai..

**Comment by Serge-NSN** [comment]
Please how can I know the files you have commented on? I don't know how to access it.

**Comment by elroykanye** [comment]
Go through the comments again. I have written the exercise number at the top of each.

**Review by elroykanye — APPROVED** [review]

**Review by elroykanye — APPROVED** [review]

**Review by elroykanye — APPROVED** [review]

**Comment by elroykanye** [comment]
I have approved these changes. 
But then, the exercise where you had to use Point (distance between 2 points) and Circle (whatever it was), required you to create classes in each case. You would have gotten my props if you did that, so you can just edit and push the changes again.

**Pull request merged**
