### PR TITLE
epong

### PR DESCRIPTION
**Pull request by Alomba-epongseh**
done.

### CODE REVIEW

**Review by elroykanye — APPROVED** [review]

**Review by elroykanye — APPROVED** [review]

**Review by elroykanye — CHANGES_REQUESTED** [review]
Ex32 
You are to do this in a function

**Review by elroykanye — CHANGES_REQUESTED** [review]
Ex31

All that the function is supposed to do is return the number of words. No need for printing.

**Review by elroykanye — APPROVED** [review]

**Review by elroykanye — CHANGES_REQUESTED** [review]
Ex46 
Passing in the length of the array is trivial. You can still get it in the function

**Review by elroykanye — CHANGES_REQUESTED** [review]
Ex48 do this in a function

**Review by elroykanye — CHANGES_REQUESTED** [review]
Ex 49
Do this in a function

**Review by elroykanye — COMMENTED** [review]
You and Mariette will explain this.
The cipher exercise.

**Review by elroykanye — APPROVED** [review]

**Review by elroykanye — CHANGES_REQUESTED** [review]
Ex 41
Do this in a function

**Comment by Alomba-epongseh** [comment]
done some corrections

**Comment by Alomba-epongseh** [comment]
done some corrections

**Review by elroykanye — APPROVED** [review]

**Review by elroykanye — CHANGES_REQUESTED** [review]
Your prime function is not accurate

**Review by elroykanye — APPROVED** [review]
I believe I will be approving just for approval's sake. There are still a lot of issue to resolve and they will be created in due time. Good work.

**Pull request merged**
